from processors.air_quality import AirQualityProcessor
from processors.time import CurrentTimeProcessor
from processors.binance import USDTProcessor
from processors.tinkoff import TickerProcessor
from processors.xiaomi import BadQualityInside